# Generated by Django 4.2 on 2023-12-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('no', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=11)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
            ],
        ),
    ]
