# Generated by Django 4.2 on 2023-12-14 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_airport_options_alter_flight_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
