# Generated by Django 4.2 on 2023-12-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_flight_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='no',
            field=models.CharField(max_length=10, unique=True, verbose_name='Code'),
        ),
    ]
