# Generated by Django 4.2 on 2023-12-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reservation_code',
            field=models.CharField(default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
